image: node:12

cache:
  key: ${CI_COMMIT_REF_SLUG}-X
  paths:
  - reveal.js

stages:
  - build
  - deploy

build:
  # only:
  #   changes:
  #     - src/**
  #     - demo/**
  #     - compile.sh
  stage: build
  script:
   - bash ./compile.sh
   - cp -v  reveal.js/css/theme/stereopticon.css src/css/theme
   - cp -rv src/css .
   - cp -rv src/lib .
  artifacts:
    name: "stereopticon-$CI_COMMIT_SHORT_SHA"
    paths:
      - lib
      - css/theme/stereopticon.css

pages:
  # only:
  #   changes:
  #     - src/**
  #     - demo/**
  #     - compile.sh
    refs:
      - master
  dependencies: 
    - build
  stage: deploy
  script:
   - mkdir public
   - cp -rv demo public
   - cp -rvL reveal.js public
   - cp -f css/theme/stereopticon.css public/reveal.js/css/theme
   - cp -f lib/font/* public/reveal.js/lib/font
   - rm -rf public/reveal.js/.git public/reveal.js/node_modules
  artifacts:
    paths:
      - public