image: node:11

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - reveal.js

pages:
  script:
   - bash ./compile.sh
   - mkdir public
   - mv demo.html public
   - cp -rv reveal.js public
   - rm -rf public/reveal.js/.git public/reveal.js/node_modules

  artifacts:
    paths:
      - public