image: node:11

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - reveal.js

stages:
  - build
  - deploy
  
build:
  stage: build
  script:
   - bash ./compile.sh
  artifacts:
    paths:
      - reveal.js/css/theme/stereopticon.css

pages:
  dependencies: 
    - build
  stage: deploy
  script:
   - mkdir public
   - cp -rv demo public
   - cp -rvL reveal.js public
   - rm -rf public/reveal.js/.git public/reveal.js/node_modules
  artifacts:
    paths:
      - public
      
keep:
  dependencies: 
    - build
  stage: deploy
  script:
   - cp -v  reveal.js/css/theme/stereopticon.css src/css/theme
   - cp -rv src/css .
   - cp -rv src/lib .
  artifacts:
    name: "stereopticon-$CI_COMMIT_SHORT_SHA"
    paths:
      - lib
      - css/theme/stereopticon.css