stages:
  - build
  - deploy

build:
  image: node:12
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-X
    paths:
    - reveal.js
  script:
   - bash ./compile.sh
   - cp -v  reveal.js/css/theme/stereopticon.css src/css/theme
   - cp -rv src/css .
   - cp -rv src/lib .
   - rm -rf reveal.js/node_modules
  artifacts:
    name: "stereopticon-$CI_COMMIT_SHORT_SHA"
    paths:
      - lib
      - css/theme/stereopticon.css
      - reveal.js

keep:
  stage: deploy
  script:
   - echo "Nothing to do"
  artifacts:
    paths:
      - lib
      - css/theme/stereopticon.css

pages:
  stage: deploy
  script:
   - mkdir public
   - cp -rv demo public
   - cp -rvL reveal.js public
   - cp -f css/theme/stereopticon.css public/reveal.js/css/theme
   - cp -f lib/font/* public/reveal.js/lib/font
   - rm -rf public/reveal.js/.git public/reveal.js/node_modules
  artifacts:
    paths:
      - public