stages:
  - build
  - deploy

build:
  image: node:12
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-X
    paths:
    - node_modules
  script:
   - bash ./compile.sh
   - cp -v  reveal.js/css/theme/stereopticon.css src/css/theme
   - cp -rv src/css .
   - cp -rv src/lib .
  artifacts:
    name: "stereopticon-$CI_COMMIT_SHORT_SHA"
    paths:
      - lib
      - css/theme/stereopticon.css
      - reveal.js

keep:
  stage: deploy
  script:
   - echo "Nothing to do"
  artifacts:
    paths:
      - lib
      - css/theme/stereopticon.css

pages:
  image: alpine
  stage: deploy
  script:
   - apk add rsync --update-cache
   - mkdir public
   - rsync -av demo public
   - rsync -av reveal.js public
   - rsync -av css/theme/stereopticon.css public/reveal.js/css/theme
   - rsync -av lib/font/* public/reveal.js/lib/font
   - rm -rf public/reveal.js/.git public/reveal.js/node_modules
  artifacts:
    paths:
      - public