stages:
  - build
  - deploy

build:
  image: docker.io/node:21
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-X
    paths:
    - node_modules
  script:
   - bash ./compile.sh
   - mkdir dist
   - cp -v  reveal.js/dist/theme/stereopticon.css dist
   - cp -rv src/fonts dist
  artifacts:
    name: "stereopticon-$CI_COMMIT_SHORT_SHA"
    paths:
      - dist
      - reveal.js

keep:
  stage: deploy
  script:
   - echo "Nothing to do"
  artifacts:
    paths:
      - dist

pages:
  image: docker.io/alpine
  stage: deploy
  script:
   - apk add rsync --update-cache
   - mkdir -p public/demo
   - rm -rf public/demo/*
   - cp -rv reveal.js public/demo
   - rsync -av demo/* public/demo
   - rsync -av dist/* public/demo/stereopticon
  artifacts:
    paths:
      - public