image: node:11

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - reveal.js

pages:
  script:
   - bash ./compile.sh
   - mkdir public
   - mv demo.html public
   - rsync -rv --exclude=node_modules --exclude=.git reveal.js public

  artifacts:
    paths:
      - public