= Changelog

== v2023-03-04

- *FIX*: Avoid double margins when a `pre` block is within a `pre` block. 
Happens eg. when `linenos` is used in asciidoctor-reveal.

== v2022-10-24

- *FIX*: Fix strangely forced grey background on images in _impact_ slides.

== v2022-09-02

- *CI*: Add separate `keep` job to only keep artifacts related to stereopticon.

== v2021-09-10

- *FIX*: Remove buggy inline code size style  + remove other buggy SCSS rule.
- *FEATURE*: Add style for asciidoctor's admonitions.
- *FEATURE*: Add rule to center captions when image is centered using asciidoctor.

== v2021-09-08

- *FIX*: Fix titles wrongly affected by `font-size-X`

== v2021-02-09

- *FIX*: Set highest priority to `.font-size-X` helper classes, to override any other font configuration from other classes.

== v2020-02-20

- *INFO*: Now aims compatibility with asciidoctor-revealjs 4.0.0 and revealjs 3.9.2.
- *INFO*: Produced `css` file is now cleaner, with version and less useless comments.
- *BREAKING CHANGE*: Renamed class `columns` to 'cols' to be more distinct from the new `columns` role of asciidoctor-revealjs.

== v2020-02-19

First official release of stereopticon! 🎉
Supports reveal.js at least until 3.8.0, and asciidoctor-revealjs at least until 3.1.0.