= Stereopticon

A reveal.js theme slightly inspired by LaTeX/Beamer.

// TODO add screenshots

== Usage in an existing reveal.js project

- Copy the `css` and `lib` folders inside a `revealjs` installation folder, and say *yes* when asking to merge the folders.
- Go in the `revealjs` folder and run: `npm run build -- css-themes`, which will produce `revealjs/css/theme/customtheme.css`.
- Now this `revealjs` folder has a new theme called `customtheme` which can be used as any other theme.

== Development and testing

In a dev environment, to test the theme:

- Run `compile.sh` that will:
    * clone reveal.js,
    * create symbolic links, in order to add our custom theme to the cloned reveal.js,
    * compile all reveal.js themes (including ours).
- Run `ruby -run -e httpd . -p 5000 -b 127.0.0.1` to start a web server.
- Open `http://localhost:5000/demo.html`, which points to our compiled theme, and admire the result.

Optional: if working in a VSCode environment, use the https://github.com/wk-j/vscode-save-and-run[Save and Run] extension to automatically run `compile.sh` after each SCSS file change.